meta:
  environment: ops-tools-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: just_install_packages
    networks:
      - name: ops-tools1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: ops-tools1
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.35.0/30
    reserved:
    - 10.244.35.1
    static:
    - 10.244.35.2

  - cloud_properties:
      name: random
    range: 10.244.35.4/30
    reserved:
    - 10.244.35.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.35.8/30
    reserved:
    - 10.244.35.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.35.12/30
    reserved:
    - 10.244.35.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.35.16/30
    reserved:
    - 10.244.35.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.35.20/30
    reserved:
    - 10.244.35.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.35.24/30
    reserved:
    - 10.244.35.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.35.28/30
    reserved:
    - 10.244.35.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.35.32/30
    reserved:
    - 10.244.35.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.35.36/30
    reserved:
    - 10.244.35.37
    static: []
